// M1 — Anonymization Export Sink.
//
// Per-column strategy applied via DuckDB SQL projection rewrite (NOT
// row-by-row JS post-processing — that would not scale to multi-million-
// row exports, and the JS string concat the v1.2 review demo'd is the
// shape of a SQL-injection / quoting-bug factory the handoff §10
// explicitly rejects).
//
// Strategies:
//   - `keep`    — emit the column verbatim.
//   - `hash`    — md5(col || salt). MD5 is built into DuckDB-wasm without
//                 an extension fetch; cryptographically adequate for the
//                 anti-re-identification threat model (which is not
//                 collision-resistance, it's "don't ship the raw value").
//                 Default for `sensitivity: 'pii'` columns.
//   - `redact`  — fixed mask `'[REDACTED]'`. Default for `sensitivity:
//                 'secret'` columns.
//   - `bucket`  — numeric/date generalisation. Numerics round to the
//                 nearest 100; dates / timestamps truncate to the month.
//                 Default for `sensitivity: 'financial'` columns.
//   - `drop`    — omit from the SELECT projection entirely.
//
// Default mapping per handoff §M1: hash for PII, bucket for Financial,
// keep for Public, redact for Secret (handoff implies, not stated;
// erring on the strictest non-destructive option). User can override
// per column in the export dialog.
//
// Salt is generated per export via `crypto.getRandomValues`, surfaced
// to the user once, and never persisted. Same-salt re-export is an
// explicit paste-it-back affordance.

import type { TypeSensitivity } from '../../taxonomy/types.ts';

export type AnonStrategy = 'keep' | 'hash' | 'redact' | 'bucket' | 'drop';

/**
 * Default strategy by sensitivity badge. Handoff §M1: hash for PII,
 * bucket for Financial. Adds: keep for Public (no badge concern),
 * redact for Secret (stricter than hash — even the hashed form is a
 * fingerprint).
 */
export function defaultStrategyForSensitivity(s: TypeSensitivity | undefined): AnonStrategy {
  if (s === 'pii') return 'hash';
  if (s === 'financial') return 'bucket';
  if (s === 'secret') return 'redact';
  return 'keep';
}

export interface AnonColumnPlan {
  columnName: string;
  /** DuckDB SQL type — drives bucket-strategy branching (numeric vs date). */
  sqlType: string;
  /** Effective strategy (after any user override). */
  strategy: AnonStrategy;
  /** Sensitivity badge as seen at plan time, recorded in the manifest. */
  sensitivity: TypeSensitivity | null;
  /** Semantic typeId, if any, recorded in the manifest. */
  typeId: string | null;
}

/**
 * Generate a per-export salt — 16 random bytes hex-encoded (32 chars).
 * Cryptographically random via the browser's `crypto.getRandomValues`.
 * Never persisted.
 */
export function generateSalt(): string {
  const bytes = new Uint8Array(16);
  crypto.getRandomValues(bytes);
  let out = '';
  for (let i = 0; i < bytes.length; i++) {
    out += (bytes[i] ?? 0).toString(16).padStart(2, '0');
  }
  return out;
}

/**
 * Quote a DuckDB identifier (column name) by wrapping in `"` and
 * doubling any internal `"`. The fundamental defense against SQL
 * injection from column names — every projection expression below
 * MUST route column references through this helper.
 */
export function quoteIdent(name: string): string {
  return `"${name.replace(/"/g, '""')}"`;
}

/**
 * Quote a SQL string literal — wrap in `'` and double internal `'`.
 * Used for the salt + the redaction mask. Salts are generated by
 * `generateSalt` (hex only), but defence-in-depth: route every
 * literal through this helper so a future code path can't introduce
 * an injection vector by passing user input directly.
 */
export function quoteLiteral(s: string): string {
  return `'${s.replace(/'/g, "''")}'`;
}

const NUMERIC_SQL_TYPES = new Set([
  'TINYINT',
  'SMALLINT',
  'INTEGER',
  'BIGINT',
  'HUGEINT',
  'UTINYINT',
  'USMALLINT',
  'UINTEGER',
  'UBIGINT',
  'FLOAT',
  'REAL',
  'DOUBLE',
  'DECIMAL',
  'NUMERIC',
]);

const DATE_LIKE_SQL_TYPES = new Set([
  'DATE',
  'TIMESTAMP',
  'TIMESTAMP_S',
  'TIMESTAMP_MS',
  'TIMESTAMP_NS',
  'TIMESTAMP WITH TIME ZONE',
  'TIMESTAMPTZ',
]);

/** Recognise numeric-shaped SQL types, including `DECIMAL(18, 2)`-style. */
export function isNumericType(sqlType: string): boolean {
  const base = sqlType.toUpperCase().split('(')[0]?.trim() ?? '';
  return NUMERIC_SQL_TYPES.has(base);
}

/** Recognise date / timestamp SQL types. */
export function isDateLikeType(sqlType: string): boolean {
  const base = sqlType.toUpperCase().split('(')[0]?.trim() ?? '';
  return DATE_LIKE_SQL_TYPES.has(base);
}

/**
 * Build the SELECT-projection clause for an anonymized export.
 *
 * Returns the contents of `SELECT <here> FROM <view>` — NOT the
 * surrounding SELECT/FROM. The caller wraps in `COPY (SELECT ...
 * FROM "cell_<id>") TO 'path.csv' (HEADER, DELIMITER ',')` or similar.
 *
 * Strategy → SQL expression:
 *   - keep     → `"col"`
 *   - hash     → `md5(COALESCE(CAST("col" AS VARCHAR), '') || '<salt>')`
 *   - redact   → `'[REDACTED]'`
 *   - bucket   → numeric: `(FLOOR(CAST("col" AS DOUBLE) / 100) * 100)`
 *                date:    `DATE_TRUNC('month', CAST("col" AS DATE))`
 *                other:   fallback to redact (so a misbadge doesn't
 *                         emit `(FLOOR(CAST(stringcol AS DOUBLE) ...))`
 *                         which would error at run time)
 *   - drop     → column is OMITTED from the projection
 *
 * If every column in the plan is `drop`, returns `NULL AS _empty` so the
 * COPY emits a single-column file with one row of NULL — the caller can
 * detect this and surface a "you dropped every column" error in the UI.
 */
export function buildAnonymizedProjection(plan: AnonColumnPlan[], salt: string): string {
  const exprs: string[] = [];
  const saltLit = quoteLiteral(salt);
  for (const col of plan) {
    if (col.strategy === 'drop') continue;
    const ident = quoteIdent(col.columnName);
    const aliased = quoteIdent(col.columnName);
    if (col.strategy === 'keep') {
      exprs.push(`${ident} AS ${aliased}`);
    } else if (col.strategy === 'hash') {
      // md5(COALESCE(CAST("col" AS VARCHAR), '') || '<salt>')
      // COALESCE-then-CAST so NULLs hash deterministically as the
      // empty-string salted form, not NULL → not-hashable.
      exprs.push(`md5(COALESCE(CAST(${ident} AS VARCHAR), '') || ${saltLit}) AS ${aliased}`);
    } else if (col.strategy === 'redact') {
      exprs.push(`${quoteLiteral('[REDACTED]')} AS ${aliased}`);
    } else if (col.strategy === 'bucket') {
      if (isNumericType(col.sqlType)) {
        exprs.push(`(FLOOR(CAST(${ident} AS DOUBLE) / 100) * 100) AS ${aliased}`);
      } else if (isDateLikeType(col.sqlType)) {
        exprs.push(`DATE_TRUNC('month', CAST(${ident} AS DATE)) AS ${aliased}`);
      } else {
        // Fallback for a misbadged string column — emit redact so the
        // export doesn't fail at run time with a CAST error.
        exprs.push(`${quoteLiteral('[REDACTED]')} AS ${aliased}`);
      }
    }
  }
  if (exprs.length === 0) {
    return 'NULL AS _empty';
  }
  return exprs.join(', ');
}

export interface AnonManifest {
  format: 'naklidata-anonymize-manifest';
  version: '1';
  exportedAt: string;
  taxonomyVersion: string;
  columns: Array<{
    name: string;
    strategy: AnonStrategy;
    sensitivity: TypeSensitivity | null;
    typeId: string | null;
  }>;
  /** Whether a salt was used. The salt itself is NEVER in the manifest. */
  saltUsed: boolean;
  /** Notes for the recipient — boilerplate explaining the manifest. */
  notes: string;
}

/**
 * Build the manifest JSON written alongside the exported file. Per
 * handoff §M1: columns + strategies + taxonomy version + NOT the salt.
 */
export function buildManifest(opts: {
  plan: AnonColumnPlan[];
  taxonomyVersion: string;
  saltUsed: boolean;
  exportedAtIso?: string;
}): AnonManifest {
  return {
    format: 'naklidata-anonymize-manifest',
    version: '1',
    exportedAt: opts.exportedAtIso ?? new Date().toISOString(),
    taxonomyVersion: opts.taxonomyVersion,
    columns: opts.plan.map((c) => ({
      name: c.columnName,
      strategy: c.strategy,
      sensitivity: c.sensitivity,
      typeId: c.typeId,
    })),
    saltUsed: opts.saltUsed,
    notes:
      'Strategies applied to this export. Salt (if used) is intentionally NOT recorded — same-salt re-export requires the user to paste the original salt back. Hash strategy uses MD5(col || salt); bucket strategy floors numerics to the nearest 100 and truncates dates to month; redact replaces with the literal "[REDACTED]"; drop omits the column entirely.',
  };
}
